#!/bin/bash
set -e

VHOST_FILE='/etc/nginx/conf.d/laravel.conf';
cp -f /etc/nginx/conf.d/template/laravel.conf $VHOST_FILE;

if [ ! -z ${SERVER_NAME+x} ]; then
    sed -i "s/#{{SERVER_NAME}}#/server_name ${SERVER_NAME//,/ };/g" $VHOST_FILE;
fi

exec "$@"
